<?php echo head(array('title' => metadata('item', array('Dublin Core', 'Title')), 'bodyclass' => 'items show')); ?>

<h1><?php echo metadata('item', array('Dublin Core', 'Title')); ?></h1>

<?php if ((get_theme_option('Item FileGallery') == 0) && metadata('item', 'has files')): ?>
<?php echo files_for_item(array('imageSize' => 'fullsize')); ?>
<?php endif; ?>

<?php echo all_element_texts('item'); ?>

<!-- print transcription, word count
echo "This is the transcription: " . $transcipt; - removed (uselessness)
 -->
<?php
  $transcipt = metadata('item', array('Item Type Metadata', 'Transcription'));
?>

<!-- Tallies the frequency of every word in "Transcript" -->
<script type="text/javascript">
var transcript = <?php echo json_encode($transcipt) ?>;
var words = search(transcript);
</script>

<div id = "wordcount">
  <!-- Value generated by wordFreq.js -->
</div>

<!-- check to see if item is an oral history/has a transcript then
 creates wordcloud; prints at approximately 17wps -->
<script>
if (words === undefined) {
    console.log("This document is not an oral history.");
} else {
  // innerHTML --> draws 'word cloud' box
  document.write('<h1>Word Cloud</h1>');
  document.write('<div id="container" style="width: 896px; height: 600px; border: 0px solid #ccc;"></div>');

  // sorts the array by key values
  words.sort(function(a, b) {
  return b.weight - a.weight;
  });

  // prints specific range of values
  $("#container").jQCloud(words.sort().slice(1, 202));
}
// console.log(transcript);
 </script>


<!-- The following returns all of the files associated with an item. -->
<?php if ((get_theme_option('Item FileGallery') == 1) && metadata('item', 'has files')): ?>
<div id="itemfiles" class="element">
    <h3><?php echo __('Files'); ?></h3>
    <div class="element-text"><?php echo files_for_item(); ?></div>
</div>
<?php endif; ?>

<!-- If the item belongs to a collection, the following creates a link to that collection. -->
<?php if (metadata('item', 'Collection Name')): ?>
<div id="collection" class="element">
    <h3><?php echo __('Collection'); ?></h3>
    <div class="element-text"><p><?php echo link_to_collection_for_item(); ?></p></div>
</div>
<?php endif; ?>

<!-- The following prints a list of all tags associated with the item -->
<?php if (metadata('item', 'has tags')): ?>
<div id="item-tags" class="element">
    <h3><?php echo __('Tags'); ?></h3>
    <div class="element-text"><?php echo tag_string('item'); ?></div>
</div>
<?php endif;?>

<!-- The following prints a citation for this item. -->
<div id="item-citation" class="element">
    <h3><?php echo __('Citation'); ?></h3>
    <div class="element-text"><?php echo metadata('item', 'citation', array('no_escape' => true)); ?></div>
</div>

<div id="item-output-formats" class="element">
    <h3><?php echo __('Output Formats'); ?></h3>
    <div class="element-text"><?php echo output_format_list(); ?></div>
</div>

<?php fire_plugin_hook('public_items_show', array('view' => $this, 'item' => $item)); ?>

<nav>
<ul class="item-pagination navigation">
    <li id="previous-item" class="previous"><?php echo link_to_previous_item_show(); ?></li>
    <li id="next-item" class="next"><?php echo link_to_next_item_show(); ?></li>
</ul>
</nav>

<?php echo foot(); ?>
